# ==========================
# Spring Boot 服务配置
# ==========================
server:
  port: 10110

# ==========================
# Spring 数据源配置
# ==========================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root                     # 数据库用户名
    password: 11111111                     # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

# ==========================
# MyBatis-Plus 配置
# ==========================
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # SQL 打印到控制台，方便调试
  type-aliases-package: ${custom.base-package}.modules.*.entity


